name: Nightly dev Test and Lint
# Used to test tango dev-branch on nightly periodically, to make sure nothing
# breaks on a new compiler and clippy version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # Every day at 6:00am

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: "clippy"
      - uses: olix0r/cargo-action-fmt/setup@v2
      - uses: Swatinem/rust-cache@v2
      - name: Running clippy
        run: cargo clippy --all-targets --all-features -p tango-bench --message-format=json | cargo-action-fmt
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2

      - name: Run Tests
        run: cargo test
